use serde::{Deserialize, Serialize};

/*
 * REST api to TON blockchain explorer
 *
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@tonkeeper.com
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AccountAddress {
    #[serde(rename = "address")]
    pub address: String,
    /// Display name. Data collected from different sources like moderation lists, dns, collections names and over.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Is this account was marked as part of scammers activity
    #[serde(rename = "is_scam")]
    pub is_scam: bool,
    #[serde(rename = "icon", skip_serializing_if = "Option::is_none")]
    pub icon: Option<String>,
    #[serde(rename = "is_wallet")]
    pub is_wallet: bool,
}

impl AccountAddress {
    pub fn new(address: String, is_scam: bool, is_wallet: bool) -> AccountAddress {
        AccountAddress {
            address,
            name: None,
            is_scam,
            icon: None,
            is_wallet,
        }
    }
}
