use serde::{Deserialize, Serialize};

/*
 * REST api to TON blockchain explorer
 *
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@tonkeeper.com
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AccountStakingInfo {
    #[serde(rename = "pool")]
    pub pool: String,
    #[serde(rename = "amount")]
    pub amount: i64,
    #[serde(rename = "pending_deposit")]
    pub pending_deposit: i64,
    #[serde(rename = "pending_withdraw")]
    pub pending_withdraw: i64,
    #[serde(rename = "ready_withdraw")]
    pub ready_withdraw: i64,
}

impl AccountStakingInfo {
    pub fn new(
        pool: String,
        amount: i64,
        pending_deposit: i64,
        pending_withdraw: i64,
        ready_withdraw: i64,
    ) -> AccountStakingInfo {
        AccountStakingInfo {
            pool,
            amount,
            pending_deposit,
            pending_withdraw,
            ready_withdraw,
        }
    }
}
