use serde::{Deserialize, Serialize};

/*
 * REST api to TON blockchain explorer
 *
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@tonkeeper.com
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ActionPhase {
    #[serde(rename = "success")]
    pub success: bool,
    #[serde(rename = "total_actions")]
    pub total_actions: i32,
    #[serde(rename = "skipped_actions")]
    pub skipped_actions: i32,
    #[serde(rename = "fwd_fees")]
    pub fwd_fees: i64,
    #[serde(rename = "total_fees")]
    pub total_fees: i64,
}

impl ActionPhase {
    pub fn new(
        success: bool,
        total_actions: i32,
        skipped_actions: i32,
        fwd_fees: i64,
        total_fees: i64,
    ) -> ActionPhase {
        ActionPhase {
            success,
            total_actions,
            skipped_actions,
            fwd_fees,
            total_fees,
        }
    }
}
