use serde::{Deserialize, Serialize};

/*
 * REST api to TON blockchain explorer
 *
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@tonkeeper.com
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApyHistory {
    #[serde(rename = "apy")]
    pub apy: f32,
    #[serde(rename = "time")]
    pub time: i32,
}

impl ApyHistory {
    pub fn new(apy: f32, time: i32) -> ApyHistory {
        ApyHistory { apy, time }
    }
}
