use serde::{Deserialize, Serialize};

/*
 * REST api to TON blockchain explorer
 *
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@tonkeeper.com
 * Generated by: https://openapi-generator.tech
 */

/// BlockchainConfig14 : The reward in nanoTons for block creation in the TON blockchain.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BlockchainConfig14 {
    #[serde(rename = "masterchain_block_fee")]
    pub masterchain_block_fee: i64,
    #[serde(rename = "basechain_block_fee")]
    pub basechain_block_fee: i64,
}

impl BlockchainConfig14 {
    /// The reward in nanoTons for block creation in the TON blockchain.
    pub fn new(masterchain_block_fee: i64, basechain_block_fee: i64) -> BlockchainConfig14 {
        BlockchainConfig14 {
            masterchain_block_fee,
            basechain_block_fee,
        }
    }
}
