use serde::{Deserialize, Serialize};

/*
 * REST api to TON blockchain explorer
 *
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@tonkeeper.com
 * Generated by: https://openapi-generator.tech
 */

/// BlockchainConfig17 : The stake parameters configuration in the TON blockchain.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BlockchainConfig17 {
    #[serde(rename = "min_stake")]
    pub min_stake: String,
    #[serde(rename = "max_stake")]
    pub max_stake: String,
    #[serde(rename = "min_total_stake")]
    pub min_total_stake: String,
    #[serde(rename = "max_stake_factor")]
    pub max_stake_factor: i64,
}

impl BlockchainConfig17 {
    /// The stake parameters configuration in the TON blockchain.
    pub fn new(
        min_stake: String,
        max_stake: String,
        min_total_stake: String,
        max_stake_factor: i64,
    ) -> BlockchainConfig17 {
        BlockchainConfig17 {
            min_stake,
            max_stake,
            min_total_stake,
            max_stake_factor,
        }
    }
}
