use serde::{Deserialize, Serialize};

/*
 * REST api to TON blockchain explorer
 *
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@tonkeeper.com
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BlockCurrencyCollectionOtherInner {
    #[serde(rename = "id")]
    pub id: i64,
    #[serde(rename = "value")]
    pub value: String,
}

impl BlockCurrencyCollectionOtherInner {
    pub fn new(id: i64, value: String) -> BlockCurrencyCollectionOtherInner {
        BlockCurrencyCollectionOtherInner { id, value }
    }
}
