use serde::{Deserialize, Serialize};

/*
 * REST api to TON blockchain explorer
 *
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@tonkeeper.com
 * Generated by: https://openapi-generator.tech
 */

/// BlockchainConfig18 : The prices for data storage.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BlockchainConfig18 {
    #[serde(rename = "storage_prices")]
    pub storage_prices: Vec<crate::rest_api::codegen::models::BlockchainConfig18StoragePricesInner>,
}

impl BlockchainConfig18 {
    /// The prices for data storage.
    pub fn new(
        storage_prices: Vec<crate::rest_api::codegen::models::BlockchainConfig18StoragePricesInner>,
    ) -> BlockchainConfig18 {
        BlockchainConfig18 { storage_prices }
    }
}
