use serde::{Deserialize, Serialize};

/*
 * REST api to TON blockchain explorer
 *
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@tonkeeper.com
 * Generated by: https://openapi-generator.tech
 */

/// BlockchainConfig24 : The cost of sending messages in the masterchain of the TON blockchain.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BlockchainConfig24 {
    #[serde(rename = "msg_forward_prices")]
    pub msg_forward_prices: Box<crate::rest_api::codegen::models::MsgForwardPrices>,
}

impl BlockchainConfig24 {
    /// The cost of sending messages in the masterchain of the TON blockchain.
    pub fn new(
        msg_forward_prices: crate::rest_api::codegen::models::MsgForwardPrices,
    ) -> BlockchainConfig24 {
        BlockchainConfig24 {
            msg_forward_prices: Box::new(msg_forward_prices),
        }
    }
}
