use serde::{Deserialize, Serialize};

/*
 * REST api to TON blockchain explorer
 *
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@tonkeeper.com
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BlockchainConfig7CurrenciesInner {
    #[serde(rename = "currency_id")]
    pub currency_id: i64,
    #[serde(rename = "amount")]
    pub amount: String,
}

impl BlockchainConfig7CurrenciesInner {
    pub fn new(currency_id: i64, amount: String) -> BlockchainConfig7CurrenciesInner {
        BlockchainConfig7CurrenciesInner {
            currency_id,
            amount,
        }
    }
}
