use serde::{Deserialize, Serialize};

/*
 * REST api to TON blockchain explorer
 *
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@tonkeeper.com
 * Generated by: https://openapi-generator.tech
 */

/// BlockchainConfig9 : List of mandatory parameters of the blockchain config.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BlockchainConfig9 {
    #[serde(rename = "mandatory_params")]
    pub mandatory_params: Vec<i32>,
}

impl BlockchainConfig9 {
    /// List of mandatory parameters of the blockchain config.
    pub fn new(mandatory_params: Vec<i32>) -> BlockchainConfig9 {
        BlockchainConfig9 { mandatory_params }
    }
}
