use serde::{Deserialize, Serialize};

/*
 * REST api to TON blockchain explorer
 *
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@tonkeeper.com
 * Generated by: https://openapi-generator.tech
 */

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum BouncePhaseType {
    #[serde(rename = "TrPhaseBounceNegfunds")]
    TrPhaseBounceNegfunds,
    #[serde(rename = "TrPhaseBounceNofunds")]
    TrPhaseBounceNofunds,
    #[serde(rename = "TrPhaseBounceOk")]
    TrPhaseBounceOk,
}

impl ToString for BouncePhaseType {
    fn to_string(&self) -> String {
        match self {
            Self::TrPhaseBounceNegfunds => String::from("TrPhaseBounceNegfunds"),
            Self::TrPhaseBounceNofunds => String::from("TrPhaseBounceNofunds"),
            Self::TrPhaseBounceOk => String::from("TrPhaseBounceOk"),
        }
    }
}

impl Default for BouncePhaseType {
    fn default() -> BouncePhaseType {
        Self::TrPhaseBounceNegfunds
    }
}
