use serde::{Deserialize, Serialize};

/*
 * REST api to TON blockchain explorer
 *
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@tonkeeper.com
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConfigProposalSetup {
    #[serde(rename = "min_tot_rounds")]
    pub min_tot_rounds: i32,
    #[serde(rename = "max_tot_rounds")]
    pub max_tot_rounds: i32,
    #[serde(rename = "min_wins")]
    pub min_wins: i32,
    #[serde(rename = "max_losses")]
    pub max_losses: i32,
    #[serde(rename = "min_store_sec")]
    pub min_store_sec: i64,
    #[serde(rename = "max_store_sec")]
    pub max_store_sec: i64,
    #[serde(rename = "bit_price")]
    pub bit_price: i64,
    #[serde(rename = "cell_price")]
    pub cell_price: i64,
}

impl ConfigProposalSetup {
    pub fn new(
        min_tot_rounds: i32,
        max_tot_rounds: i32,
        min_wins: i32,
        max_losses: i32,
        min_store_sec: i64,
        max_store_sec: i64,
        bit_price: i64,
        cell_price: i64,
    ) -> ConfigProposalSetup {
        ConfigProposalSetup {
            min_tot_rounds,
            max_tot_rounds,
            min_wins,
            max_losses,
            min_store_sec,
            max_store_sec,
            bit_price,
            cell_price,
        }
    }
}
