use serde::{Deserialize, Serialize};

/*
 * REST api to TON blockchain explorer
 *
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@tonkeeper.com
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreditPhase {
    #[serde(rename = "fees_collected")]
    pub fees_collected: i64,
    #[serde(rename = "credit")]
    pub credit: i64,
}

impl CreditPhase {
    pub fn new(fees_collected: i64, credit: i64) -> CreditPhase {
        CreditPhase {
            fees_collected,
            credit,
        }
    }
}
