use serde::{Deserialize, Serialize};

/*
 * REST api to TON blockchain explorer
 *
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@tonkeeper.com
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct DecodedMessageExtInMsgDecodedWalletHighloadV2 {
    #[serde(rename = "subwallet_id")]
    pub subwallet_id: i32,
    #[serde(rename = "bounded_query_id")]
    pub bounded_query_id: String,
    #[serde(rename = "raw_messages")]
    pub raw_messages: Vec<crate::rest_api::codegen::models::DecodedRawMessage>,
}

impl DecodedMessageExtInMsgDecodedWalletHighloadV2 {
    pub fn new(
        subwallet_id: i32,
        bounded_query_id: String,
        raw_messages: Vec<crate::rest_api::codegen::models::DecodedRawMessage>,
    ) -> DecodedMessageExtInMsgDecodedWalletHighloadV2 {
        DecodedMessageExtInMsgDecodedWalletHighloadV2 {
            subwallet_id,
            bounded_query_id,
            raw_messages,
        }
    }
}
