use serde::{Deserialize, Serialize};

/*
 * REST api to TON blockchain explorer
 *
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@tonkeeper.com
 * Generated by: https://openapi-generator.tech
 */

/// DepositStakeAction : validator's participation in elections

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct DepositStakeAction {
    #[serde(rename = "amount")]
    pub amount: i64,
    #[serde(rename = "staker")]
    pub staker: Box<crate::rest_api::codegen::models::AccountAddress>,
    #[serde(rename = "pool")]
    pub pool: Box<crate::rest_api::codegen::models::AccountAddress>,
    #[serde(rename = "implementation")]
    pub implementation: crate::rest_api::codegen::models::PoolImplementationType,
}

impl DepositStakeAction {
    /// validator's participation in elections
    pub fn new(
        amount: i64,
        staker: crate::rest_api::codegen::models::AccountAddress,
        pool: crate::rest_api::codegen::models::AccountAddress,
        implementation: crate::rest_api::codegen::models::PoolImplementationType,
    ) -> DepositStakeAction {
        DepositStakeAction {
            amount,
            staker: Box::new(staker),
            pool: Box::new(pool),
            implementation,
        }
    }
}
