use serde::{Deserialize, Serialize};

/*
 * REST api to TON blockchain explorer
 *
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@tonkeeper.com
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct DomainBids {
    #[serde(rename = "data")]
    pub data: Vec<crate::rest_api::codegen::models::DomainBid>,
}

impl DomainBids {
    pub fn new(data: Vec<crate::rest_api::codegen::models::DomainBid>) -> DomainBids {
        DomainBids { data }
    }
}
