use serde::{Deserialize, Serialize};

/*
 * REST api to TON blockchain explorer
 *
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@tonkeeper.com
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ElectionsDepositStakeAction {
    #[serde(rename = "amount")]
    pub amount: i64,
    #[serde(rename = "staker")]
    pub staker: Box<crate::rest_api::codegen::models::AccountAddress>,
}

impl ElectionsDepositStakeAction {
    pub fn new(
        amount: i64,
        staker: crate::rest_api::codegen::models::AccountAddress,
    ) -> ElectionsDepositStakeAction {
        ElectionsDepositStakeAction {
            amount,
            staker: Box::new(staker),
        }
    }
}
