use serde::{Deserialize, Serialize};

/*
 * REST api to TON blockchain explorer
 *
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@tonkeeper.com
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct EncryptedComment {
    #[serde(rename = "encryption_type")]
    pub encryption_type: String,
    #[serde(rename = "cipher_text")]
    pub cipher_text: String,
}

impl EncryptedComment {
    pub fn new(encryption_type: String, cipher_text: String) -> EncryptedComment {
        EncryptedComment {
            encryption_type,
            cipher_text,
        }
    }
}
