use serde::{Deserialize, Serialize};

/*
 * REST api to TON blockchain explorer
 *
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@tonkeeper.com
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Event {
    #[serde(rename = "event_id")]
    pub event_id: String,
    #[serde(rename = "timestamp")]
    pub timestamp: i64,
    #[serde(rename = "actions")]
    pub actions: Vec<crate::rest_api::codegen::models::Action>,
    #[serde(rename = "value_flow")]
    pub value_flow: Vec<crate::rest_api::codegen::models::ValueFlow>,
    /// scam
    #[serde(rename = "is_scam")]
    pub is_scam: bool,
    #[serde(rename = "lt")]
    pub lt: i64,
    /// Event is not finished yet. Transactions still happening
    #[serde(rename = "in_progress")]
    pub in_progress: bool,
}

impl Event {
    pub fn new(
        event_id: String,
        timestamp: i64,
        actions: Vec<crate::rest_api::codegen::models::Action>,
        value_flow: Vec<crate::rest_api::codegen::models::ValueFlow>,
        is_scam: bool,
        lt: i64,
        in_progress: bool,
    ) -> Event {
        Event {
            event_id,
            timestamp,
            actions,
            value_flow,
            is_scam,
            lt,
            in_progress,
        }
    }
}
