use serde::{Deserialize, Serialize};

/*
 * REST api to TON blockchain explorer
 *
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@tonkeeper.com
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetAccountPublicKey200Response {
    #[serde(rename = "public_key")]
    pub public_key: String,
}

impl GetAccountPublicKey200Response {
    pub fn new(public_key: String) -> GetAccountPublicKey200Response {
        GetAccountPublicKey200Response { public_key }
    }
}
