use serde::{Deserialize, Serialize};

/*
 * REST api to TON blockchain explorer
 *
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@tonkeeper.com
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetRawBlockProof200ResponseStepsInnerLiteServerBlockLinkForwardSignatures {
    #[serde(rename = "validator_set_hash")]
    pub validator_set_hash: i32,
    #[serde(rename = "catchain_seqno")]
    pub catchain_seqno: i32,
    #[serde(rename = "signatures")]
    pub signatures: Vec<crate::rest_api::codegen::models::GetRawBlockProof200ResponseStepsInnerLiteServerBlockLinkForwardSignaturesSignaturesInner>,
}

impl GetRawBlockProof200ResponseStepsInnerLiteServerBlockLinkForwardSignatures {
    pub fn new(
        validator_set_hash: i32,
        catchain_seqno: i32,
        signatures: Vec<crate::rest_api::codegen::models::GetRawBlockProof200ResponseStepsInnerLiteServerBlockLinkForwardSignaturesSignaturesInner>,
    ) -> GetRawBlockProof200ResponseStepsInnerLiteServerBlockLinkForwardSignatures {
        GetRawBlockProof200ResponseStepsInnerLiteServerBlockLinkForwardSignatures {
            validator_set_hash,
            catchain_seqno,
            signatures,
        }
    }
}
