use serde::{Deserialize, Serialize};

/*
 * REST api to TON blockchain explorer
 *
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@tonkeeper.com
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetStakingPoolHistory200Response {
    #[serde(rename = "apy")]
    pub apy: Vec<crate::rest_api::codegen::models::ApyHistory>,
}

impl GetStakingPoolHistory200Response {
    pub fn new(
        apy: Vec<crate::rest_api::codegen::models::ApyHistory>,
    ) -> GetStakingPoolHistory200Response {
        GetStakingPoolHistory200Response { apy }
    }
}
