use serde::{Deserialize, Serialize};

/*
 * REST api to TON blockchain explorer
 *
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@tonkeeper.com
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetAccountDiff200Response {
    #[serde(rename = "balance_change")]
    pub balance_change: i64,
}

impl GetAccountDiff200Response {
    pub fn new(balance_change: i64) -> GetAccountDiff200Response {
        GetAccountDiff200Response { balance_change }
    }
}
