use serde::{Deserialize, Serialize};

/*
 * REST api to TON blockchain explorer
 *
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@tonkeeper.com
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetStakingPoolInfo200Response {
    #[serde(rename = "implementation")]
    pub implementation: Box<crate::rest_api::codegen::models::PoolImplementation>,
    #[serde(rename = "pool")]
    pub pool: Box<crate::rest_api::codegen::models::PoolInfo>,
}

impl GetStakingPoolInfo200Response {
    pub fn new(
        implementation: crate::rest_api::codegen::models::PoolImplementation,
        pool: crate::rest_api::codegen::models::PoolInfo,
    ) -> GetStakingPoolInfo200Response {
        GetStakingPoolInfo200Response {
            implementation: Box::new(implementation),
            pool: Box::new(pool),
        }
    }
}
