use serde::{Deserialize, Serialize};

/*
 * REST api to TON blockchain explorer
 *
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@tonkeeper.com
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetRates200Response {
    #[serde(rename = "rates")]
    pub rates: ::std::collections::HashMap<String, crate::rest_api::codegen::models::TokenRates>,
}

impl GetRates200Response {
    pub fn new(
        rates: ::std::collections::HashMap<String, crate::rest_api::codegen::models::TokenRates>,
    ) -> GetRates200Response {
        GetRates200Response { rates }
    }
}
