use serde::{Deserialize, Serialize};

/*
 * REST api to TON blockchain explorer
 *
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@tonkeeper.com
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct JettonPreview {
    #[serde(rename = "address")]
    pub address: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "symbol")]
    pub symbol: String,
    #[serde(rename = "decimals")]
    pub decimals: i32,
    #[serde(rename = "image")]
    pub image: String,
    #[serde(rename = "verification")]
    pub verification: crate::rest_api::codegen::models::JettonVerificationType,
}

impl JettonPreview {
    pub fn new(
        address: String,
        name: String,
        symbol: String,
        decimals: i32,
        image: String,
        verification: crate::rest_api::codegen::models::JettonVerificationType,
    ) -> JettonPreview {
        JettonPreview {
            address,
            name,
            symbol,
            decimals,
            image,
            verification,
        }
    }
}
