use serde::{Deserialize, Serialize};

/*
 * REST api to TON blockchain explorer
 *
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@tonkeeper.com
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PoolImplementation {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "description")]
    pub description: String,
    #[serde(rename = "url")]
    pub url: String,
    #[serde(rename = "socials")]
    pub socials: Vec<String>,
}

impl PoolImplementation {
    pub fn new(
        name: String,
        description: String,
        url: String,
        socials: Vec<String>,
    ) -> PoolImplementation {
        PoolImplementation {
            name,
            description,
            url,
            socials,
        }
    }
}
