use serde::{Deserialize, Serialize};

/*
 * REST api to TON blockchain explorer
 *
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@tonkeeper.com
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Refund {
    #[serde(rename = "type")]
    pub r#type: Type,
    #[serde(rename = "origin")]
    pub origin: String,
}

impl Refund {
    pub fn new(r#type: Type, origin: String) -> Refund {
        Refund { r#type, origin }
    }
}

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "DNS.ton")]
    DnsPeriodTon,
    #[serde(rename = "DNS.tg")]
    DnsPeriodTg,
    #[serde(rename = "GetGems")]
    GetGems,
}

impl Default for Type {
    fn default() -> Type {
        Self::DnsPeriodTon
    }
}
