use serde::{Deserialize, Serialize};

/*
 * REST api to TON blockchain explorer
 *
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@tonkeeper.com
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SendBlockchainMessageRequest {
    #[serde(rename = "boc", skip_serializing_if = "Option::is_none")]
    pub boc: Option<String>,
    #[serde(rename = "batch", skip_serializing_if = "Option::is_none")]
    pub batch: Option<Vec<String>>,
}

impl SendBlockchainMessageRequest {
    pub fn new() -> SendBlockchainMessageRequest {
        SendBlockchainMessageRequest {
            boc: None,
            batch: None,
        }
    }
}
