use serde::{Deserialize, Serialize};

/*
 * REST api to TON blockchain explorer
 *
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@tonkeeper.com
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TokenRates {
    #[serde(rename = "prices", skip_serializing_if = "Option::is_none")]
    pub prices: Option<::std::collections::HashMap<String, f32>>,
    #[serde(rename = "diff_24h", skip_serializing_if = "Option::is_none")]
    pub diff_24h: Option<::std::collections::HashMap<String, String>>,
    #[serde(rename = "diff_7d", skip_serializing_if = "Option::is_none")]
    pub diff_7d: Option<::std::collections::HashMap<String, String>>,
    #[serde(rename = "diff_30d", skip_serializing_if = "Option::is_none")]
    pub diff_30d: Option<::std::collections::HashMap<String, String>>,
}

impl TokenRates {
    pub fn new() -> TokenRates {
        TokenRates {
            prices: None,
            diff_24h: None,
            diff_7d: None,
            diff_30d: None,
        }
    }
}
