use serde::{Deserialize, Serialize};

/*
 * REST api to TON blockchain explorer
 *
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@tonkeeper.com
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TonConnectProofRequestProof {
    #[serde(rename = "timestamp")]
    pub timestamp: i64,
    #[serde(rename = "domain")]
    pub domain: Box<crate::rest_api::codegen::models::TonConnectProofRequestProofDomain>,
    #[serde(rename = "signature")]
    pub signature: String,
    #[serde(rename = "payload")]
    pub payload: String,
    #[serde(rename = "state_init", skip_serializing_if = "Option::is_none")]
    pub state_init: Option<String>,
}

impl TonConnectProofRequestProof {
    pub fn new(
        timestamp: i64,
        domain: crate::rest_api::codegen::models::TonConnectProofRequestProofDomain,
        signature: String,
        payload: String,
    ) -> TonConnectProofRequestProof {
        TonConnectProofRequestProof {
            timestamp,
            domain: Box::new(domain),
            signature,
            payload,
            state_init: None,
        }
    }
}
