use serde::{Deserialize, Serialize};
use tonlib::address::TonAddress;

/*
 * REST api to TON blockchain explorer
 *
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@tonkeeper.com
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TonConnectProofRequest {
    #[serde(rename = "address")]
    pub address: TonAddress,
    #[serde(rename = "proof")]
    pub proof: Box<crate::rest_api::codegen::models::TonConnectProofRequestProof>,
}

impl TonConnectProofRequest {
    pub fn new(
        address: TonAddress,
        proof: crate::rest_api::codegen::models::TonConnectProofRequestProof,
    ) -> TonConnectProofRequest {
        TonConnectProofRequest {
            address,
            proof: Box::new(proof),
        }
    }
}
