use serde::{Deserialize, Serialize};

/*
 * REST api to TON blockchain explorer
 *
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@tonkeeper.com
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TonConnectProofRequestProofDomain {
    #[serde(rename = "length_bytes", skip_serializing_if = "Option::is_none")]
    pub length_bytes: Option<i32>,
    #[serde(rename = "value")]
    pub value: String,
}

impl TonConnectProofRequestProofDomain {
    pub fn new(value: String) -> TonConnectProofRequestProofDomain {
        TonConnectProofRequestProofDomain {
            length_bytes: None,
            value,
        }
    }
}
