use serde::{Deserialize, Serialize};

/*
 * REST api to TON blockchain explorer
 *
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@tonkeeper.com
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TraceId {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "utime")]
    pub utime: i32,
}

impl TraceId {
    pub fn new(id: String, utime: i32) -> TraceId {
        TraceId { id, utime }
    }
}
