use serde::{Deserialize, Serialize};

/*
 * REST api to TON blockchain explorer
 *
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@tonkeeper.com
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TraceIds {
    #[serde(rename = "traces")]
    pub traces: Vec<crate::rest_api::codegen::models::TraceId>,
}

impl TraceIds {
    pub fn new(traces: Vec<crate::rest_api::codegen::models::TraceId>) -> TraceIds {
        TraceIds { traces }
    }
}
