use serde::{Deserialize, Serialize};

/*
 * REST api to TON blockchain explorer
 *
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@tonkeeper.com
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct UnSubscriptionAction {
    #[serde(rename = "subscriber")]
    pub subscriber: Box<crate::rest_api::codegen::models::AccountAddress>,
    #[serde(rename = "subscription")]
    pub subscription: String,
    #[serde(rename = "beneficiary")]
    pub beneficiary: Box<crate::rest_api::codegen::models::AccountAddress>,
}

impl UnSubscriptionAction {
    pub fn new(
        subscriber: crate::rest_api::codegen::models::AccountAddress,
        subscription: String,
        beneficiary: crate::rest_api::codegen::models::AccountAddress,
    ) -> UnSubscriptionAction {
        UnSubscriptionAction {
            subscriber: Box::new(subscriber),
            subscription,
            beneficiary: Box::new(beneficiary),
        }
    }
}
