use serde::{Deserialize, Serialize};

/*
 * REST api to TON blockchain explorer
 *
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@tonkeeper.com
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ValidatorsSetListInner {
    #[serde(rename = "public_key")]
    pub public_key: String,
    #[serde(rename = "weight")]
    pub weight: i64,
    #[serde(rename = "adnl_addr", skip_serializing_if = "Option::is_none")]
    pub adnl_addr: Option<String>,
}

impl ValidatorsSetListInner {
    pub fn new(public_key: String, weight: i64) -> ValidatorsSetListInner {
        ValidatorsSetListInner {
            public_key,
            weight,
            adnl_addr: None,
        }
    }
}
