use serde::{Deserialize, Serialize};

/*
 * REST api to TON blockchain explorer
 *
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@tonkeeper.com
 * Generated by: https://openapi-generator.tech
 */

/// WithdrawStakeRequestAction : validator's participation in elections

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct WithdrawStakeRequestAction {
    #[serde(rename = "amount", skip_serializing_if = "Option::is_none")]
    pub amount: Option<i64>,
    #[serde(rename = "staker")]
    pub staker: Box<crate::rest_api::codegen::models::AccountAddress>,
    #[serde(rename = "pool")]
    pub pool: Box<crate::rest_api::codegen::models::AccountAddress>,
    #[serde(rename = "implementation")]
    pub implementation: crate::rest_api::codegen::models::PoolImplementationType,
}

impl WithdrawStakeRequestAction {
    /// validator's participation in elections
    pub fn new(
        staker: crate::rest_api::codegen::models::AccountAddress,
        pool: crate::rest_api::codegen::models::AccountAddress,
        implementation: crate::rest_api::codegen::models::PoolImplementationType,
    ) -> WithdrawStakeRequestAction {
        WithdrawStakeRequestAction {
            amount: None,
            staker: Box::new(staker),
            pool: Box::new(pool),
            implementation,
        }
    }
}
