/*
 * REST api to TON blockchain explorer
 *
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@tonkeeper.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AccountStorageInfo {
    #[serde(rename = "used_cells")]
    pub used_cells: i64,
    #[serde(rename = "used_bits")]
    pub used_bits: i64,
    #[serde(rename = "used_public_cells")]
    pub used_public_cells: i64,
    #[serde(rename = "last_paid")]
    pub last_paid: i64,
    #[serde(rename = "due_payment")]
    pub due_payment: i64,
}

impl AccountStorageInfo {
    pub fn new(used_cells: i64, used_bits: i64, used_public_cells: i64, last_paid: i64, due_payment: i64) -> AccountStorageInfo {
        AccountStorageInfo {
            used_cells,
            used_bits,
            used_public_cells,
            last_paid,
            due_payment,
        }
    }
}


