/*
 * REST api to TON blockchain explorer
 *
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@tonkeeper.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AddressParse200Response {
    #[serde(rename = "raw_form")]
    pub raw_form: String,
    #[serde(rename = "bounceable")]
    pub bounceable: Box<crate::models::AddressParse200ResponseBounceable>,
    #[serde(rename = "non_bounceable")]
    pub non_bounceable: Box<crate::models::AddressParse200ResponseBounceable>,
    #[serde(rename = "given_type")]
    pub given_type: String,
    #[serde(rename = "test_only")]
    pub test_only: bool,
}

impl AddressParse200Response {
    pub fn new(raw_form: String, bounceable: crate::models::AddressParse200ResponseBounceable, non_bounceable: crate::models::AddressParse200ResponseBounceable, given_type: String, test_only: bool) -> AddressParse200Response {
        AddressParse200Response {
            raw_form,
            bounceable: Box::new(bounceable),
            non_bounceable: Box::new(non_bounceable),
            given_type,
            test_only,
        }
    }
}


