/*
 * REST api to TON blockchain explorer
 *
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@tonkeeper.com
 * Generated by: https://openapi-generator.tech
 */

/// BlockchainConfig11 : This parameter indicates under what conditions proposals to change the TON configuration are accepted.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BlockchainConfig11 {
    #[serde(rename = "normal_params")]
    pub normal_params: Box<crate::models::ConfigProposalSetup>,
    #[serde(rename = "critical_params")]
    pub critical_params: Box<crate::models::ConfigProposalSetup>,
}

impl BlockchainConfig11 {
    /// This parameter indicates under what conditions proposals to change the TON configuration are accepted.
    pub fn new(normal_params: crate::models::ConfigProposalSetup, critical_params: crate::models::ConfigProposalSetup) -> BlockchainConfig11 {
        BlockchainConfig11 {
            normal_params: Box::new(normal_params),
            critical_params: Box::new(critical_params),
        }
    }
}


