/*
 * REST api to TON blockchain explorer
 *
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@tonkeeper.com
 * Generated by: https://openapi-generator.tech
 */

/// BlockchainConfig7 : The volume of each of the additional currencies in circulation.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BlockchainConfig7 {
    #[serde(rename = "currencies")]
    pub currencies: Vec<crate::models::BlockchainConfig7CurrenciesInner>,
}

impl BlockchainConfig7 {
    /// The volume of each of the additional currencies in circulation.
    pub fn new(currencies: Vec<crate::models::BlockchainConfig7CurrenciesInner>) -> BlockchainConfig7 {
        BlockchainConfig7 {
            currencies,
        }
    }
}


