/*
 * REST api to TON blockchain explorer
 *
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@tonkeeper.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct DecodedRawMessageMessage {
    #[serde(rename = "boc")]
    pub boc: String,
    #[serde(rename = "decoded_op_name", skip_serializing_if = "Option::is_none")]
    pub decoded_op_name: Option<String>,
    #[serde(rename = "op_code", skip_serializing_if = "Option::is_none")]
    pub op_code: Option<String>,
    #[serde(rename = "decoded_body", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub decoded_body: Option<Option<serde_json::Value>>,
}

impl DecodedRawMessageMessage {
    pub fn new(boc: String) -> DecodedRawMessageMessage {
        DecodedRawMessageMessage {
            boc,
            decoded_op_name: None,
            op_code: None,
            decoded_body: None,
        }
    }
}


