/*
 * REST api to TON blockchain explorer
 *
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@tonkeeper.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetRawBlockchainBlockHeader200Response {
    #[serde(rename = "id")]
    pub id: Box<crate::models::BlockRaw>,
    #[serde(rename = "mode")]
    pub mode: i32,
    #[serde(rename = "header_proof")]
    pub header_proof: String,
}

impl GetRawBlockchainBlockHeader200Response {
    pub fn new(id: crate::models::BlockRaw, mode: i32, header_proof: String) -> GetRawBlockchainBlockHeader200Response {
        GetRawBlockchainBlockHeader200Response {
            id: Box::new(id),
            mode,
            header_proof,
        }
    }
}


