/*
 * REST api to TON blockchain explorer
 *
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@tonkeeper.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetStakingPools200Response {
    #[serde(rename = "pools")]
    pub pools: Vec<crate::models::PoolInfo>,
    #[serde(rename = "implementations")]
    pub implementations: ::std::collections::HashMap<String, crate::models::PoolImplementation>,
}

impl GetStakingPools200Response {
    pub fn new(pools: Vec<crate::models::PoolInfo>, implementations: ::std::collections::HashMap<String, crate::models::PoolImplementation>) -> GetStakingPools200Response {
        GetStakingPools200Response {
            pools,
            implementations,
        }
    }
}


