/*
 * REST api to TON blockchain explorer
 *
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@tonkeeper.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ImagePreview {
    #[serde(rename = "resolution")]
    pub resolution: String,
    #[serde(rename = "url")]
    pub url: String,
}

impl ImagePreview {
    pub fn new(resolution: String, url: String) -> ImagePreview {
        ImagePreview {
            resolution,
            url,
        }
    }
}


