/*
 * REST api to TON blockchain explorer
 *
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@tonkeeper.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct MessageConsequences {
    #[serde(rename = "trace")]
    pub trace: Box<crate::models::Trace>,
    #[serde(rename = "risk")]
    pub risk: Box<crate::models::Risk>,
    #[serde(rename = "event")]
    pub event: Box<crate::models::AccountEvent>,
}

impl MessageConsequences {
    pub fn new(trace: crate::models::Trace, risk: crate::models::Risk, event: crate::models::AccountEvent) -> MessageConsequences {
        MessageConsequences {
            trace: Box::new(trace),
            risk: Box::new(risk),
            event: Box::new(event),
        }
    }
}


