/*
 * REST api to TON blockchain explorer
 *
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@tonkeeper.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct RawBlockchainConfig {
    #[serde(rename = "config")]
    pub config: ::std::collections::HashMap<String, serde_json::Value>,
}

impl RawBlockchainConfig {
    pub fn new(config: ::std::collections::HashMap<String, serde_json::Value>) -> RawBlockchainConfig {
        RawBlockchainConfig {
            config,
        }
    }
}


