/*
 * REST api to TON blockchain explorer
 *
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@tonkeeper.com
 * Generated by: https://openapi-generator.tech
 */

/// Risk : Risk specifies assets that could be lost if a message would be sent to a malicious smart contract. It makes sense to understand the risk BEFORE sending a message to the blockchain.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Risk {
    /// transfer all the remaining balance of the wallet.
    #[serde(rename = "transfer_all_remaining_balance")]
    pub transfer_all_remaining_balance: bool,
    #[serde(rename = "ton")]
    pub ton: i64,
    #[serde(rename = "jettons")]
    pub jettons: Vec<crate::models::JettonQuantity>,
    #[serde(rename = "nfts")]
    pub nfts: Vec<crate::models::NftItem>,
}

impl Risk {
    /// Risk specifies assets that could be lost if a message would be sent to a malicious smart contract. It makes sense to understand the risk BEFORE sending a message to the blockchain.
    pub fn new(transfer_all_remaining_balance: bool, ton: i64, jettons: Vec<crate::models::JettonQuantity>, nfts: Vec<crate::models::NftItem>) -> Risk {
        Risk {
            transfer_all_remaining_balance,
            ton,
            jettons,
            nfts,
        }
    }
}


