/*
 * REST api to TON blockchain explorer
 *
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@tonkeeper.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BlockParamLimits {
    #[serde(rename = "underload")]
    pub underload: i64,
    #[serde(rename = "soft_limit")]
    pub soft_limit: i64,
    #[serde(rename = "hard_limit")]
    pub hard_limit: i64,
}

impl BlockParamLimits {
    pub fn new(underload: i64, soft_limit: i64, hard_limit: i64) -> BlockParamLimits {
        BlockParamLimits {
            underload,
            soft_limit,
            hard_limit,
        }
    }
}


