/*
 * REST api to TON blockchain explorer
 *
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@tonkeeper.com
 * Generated by: https://openapi-generator.tech
 */

/// BlockchainConfig13 : The cost of filing complaints about incorrect operation of validators.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BlockchainConfig13 {
    #[serde(rename = "deposit")]
    pub deposit: i64,
    #[serde(rename = "bit_price")]
    pub bit_price: i64,
    #[serde(rename = "cell_price")]
    pub cell_price: i64,
}

impl BlockchainConfig13 {
    /// The cost of filing complaints about incorrect operation of validators.
    pub fn new(deposit: i64, bit_price: i64, cell_price: i64) -> BlockchainConfig13 {
        BlockchainConfig13 {
            deposit,
            bit_price,
            cell_price,
        }
    }
}


