/*
 * REST api to TON blockchain explorer
 *
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@tonkeeper.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct DomainInfo {
    #[serde(rename = "name")]
    pub name: String,
    /// date of expiring. optional. not all domain in ton has expiration date
    #[serde(rename = "expiring_at", skip_serializing_if = "Option::is_none")]
    pub expiring_at: Option<i64>,
    #[serde(rename = "item", skip_serializing_if = "Option::is_none")]
    pub item: Option<Box<crate::models::NftItem>>,
}

impl DomainInfo {
    pub fn new(name: String) -> DomainInfo {
        DomainInfo {
            name,
            expiring_at: None,
            item: None,
        }
    }
}


