/*
 * REST api to TON blockchain explorer
 *
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@tonkeeper.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetStorageProviders200Response {
    #[serde(rename = "providers")]
    pub providers: Vec<crate::models::StorageProvider>,
}

impl GetStorageProviders200Response {
    pub fn new(providers: Vec<crate::models::StorageProvider>) -> GetStorageProviders200Response {
        GetStorageProviders200Response {
            providers,
        }
    }
}


