/*
 * REST api to TON blockchain explorer
 *
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@tonkeeper.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetRawMasterchainInfoExt200Response {
    #[serde(rename = "mode")]
    pub mode: i32,
    #[serde(rename = "version")]
    pub version: i32,
    #[serde(rename = "capabilities")]
    pub capabilities: i32,
    #[serde(rename = "last")]
    pub last: Box<crate::models::BlockRaw>,
    #[serde(rename = "last_utime")]
    pub last_utime: i32,
    #[serde(rename = "now")]
    pub now: i32,
    #[serde(rename = "state_root_hash")]
    pub state_root_hash: String,
    #[serde(rename = "init")]
    pub init: Box<crate::models::InitStateRaw>,
}

impl GetRawMasterchainInfoExt200Response {
    pub fn new(mode: i32, version: i32, capabilities: i32, last: crate::models::BlockRaw, last_utime: i32, now: i32, state_root_hash: String, init: crate::models::InitStateRaw) -> GetRawMasterchainInfoExt200Response {
        GetRawMasterchainInfoExt200Response {
            mode,
            version,
            capabilities,
            last: Box::new(last),
            last_utime,
            now,
            state_root_hash,
            init: Box::new(init),
        }
    }
}


