/*
 * REST api to TON blockchain explorer
 *
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@tonkeeper.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetRawBlockProof200ResponseStepsInner {
    #[serde(rename = "lite_server_block_link_back")]
    pub lite_server_block_link_back: Box<crate::models::GetRawBlockProof200ResponseStepsInnerLiteServerBlockLinkBack>,
    #[serde(rename = "lite_server_block_link_forward")]
    pub lite_server_block_link_forward: Box<crate::models::GetRawBlockProof200ResponseStepsInnerLiteServerBlockLinkForward>,
}

impl GetRawBlockProof200ResponseStepsInner {
    pub fn new(lite_server_block_link_back: crate::models::GetRawBlockProof200ResponseStepsInnerLiteServerBlockLinkBack, lite_server_block_link_forward: crate::models::GetRawBlockProof200ResponseStepsInnerLiteServerBlockLinkForward) -> GetRawBlockProof200ResponseStepsInner {
        GetRawBlockProof200ResponseStepsInner {
            lite_server_block_link_back: Box::new(lite_server_block_link_back),
            lite_server_block_link_forward: Box::new(lite_server_block_link_forward),
        }
    }
}


