/*
 * REST api to TON blockchain explorer
 *
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@tonkeeper.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct JettonMintAction {
    #[serde(rename = "recipient")]
    pub recipient: Box<crate::models::AccountAddress>,
    #[serde(rename = "recipients_wallet")]
    pub recipients_wallet: String,
    /// amount in quanta of tokens
    #[serde(rename = "amount")]
    pub amount: String,
    #[serde(rename = "jetton")]
    pub jetton: Box<crate::models::JettonPreview>,
}

impl JettonMintAction {
    pub fn new(recipient: crate::models::AccountAddress, recipients_wallet: String, amount: String, jetton: crate::models::JettonPreview) -> JettonMintAction {
        JettonMintAction {
            recipient: Box::new(recipient),
            recipients_wallet,
            amount,
            jetton: Box::new(jetton),
        }
    }
}


