/*
 * REST api to TON blockchain explorer
 *
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@tonkeeper.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct JettonHoldersAddressesInner {
    #[serde(rename = "address")]
    pub address: String,
    #[serde(rename = "owner")]
    pub owner: Box<crate::models::AccountAddress>,
    #[serde(rename = "balance")]
    pub balance: String,
}

impl JettonHoldersAddressesInner {
    pub fn new(address: String, owner: crate::models::AccountAddress, balance: String) -> JettonHoldersAddressesInner {
        JettonHoldersAddressesInner {
            address,
            owner: Box::new(owner),
            balance,
        }
    }
}


