/*
 * REST api to TON blockchain explorer
 *
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@tonkeeper.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct MisbehaviourPunishmentConfig {
    #[serde(rename = "default_flat_fine")]
    pub default_flat_fine: i64,
    #[serde(rename = "default_proportional_fine")]
    pub default_proportional_fine: i64,
    #[serde(rename = "severity_flat_mult")]
    pub severity_flat_mult: i32,
    #[serde(rename = "severity_proportional_mult")]
    pub severity_proportional_mult: i32,
    #[serde(rename = "unpunishable_interval")]
    pub unpunishable_interval: i32,
    #[serde(rename = "long_interval")]
    pub long_interval: i32,
    #[serde(rename = "long_flat_mult")]
    pub long_flat_mult: i32,
    #[serde(rename = "long_proportional_mult")]
    pub long_proportional_mult: i32,
    #[serde(rename = "medium_interval")]
    pub medium_interval: i32,
    #[serde(rename = "medium_flat_mult")]
    pub medium_flat_mult: i32,
    #[serde(rename = "medium_proportional_mult")]
    pub medium_proportional_mult: i32,
}

impl MisbehaviourPunishmentConfig {
    pub fn new(default_flat_fine: i64, default_proportional_fine: i64, severity_flat_mult: i32, severity_proportional_mult: i32, unpunishable_interval: i32, long_interval: i32, long_flat_mult: i32, long_proportional_mult: i32, medium_interval: i32, medium_flat_mult: i32, medium_proportional_mult: i32) -> MisbehaviourPunishmentConfig {
        MisbehaviourPunishmentConfig {
            default_flat_fine,
            default_proportional_fine,
            severity_flat_mult,
            severity_proportional_mult,
            unpunishable_interval,
            long_interval,
            long_flat_mult,
            long_proportional_mult,
            medium_interval,
            medium_flat_mult,
            medium_proportional_mult,
        }
    }
}


