/*
 * REST api to TON blockchain explorer
 *
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@tonkeeper.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Seqno {
    #[serde(rename = "seqno")]
    pub seqno: i32,
}

impl Seqno {
    pub fn new(seqno: i32) -> Seqno {
        Seqno {
            seqno,
        }
    }
}


