/*
 * REST api to TON blockchain explorer
 *
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@tonkeeper.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SizeLimitsConfig {
    #[serde(rename = "max_msg_bits")]
    pub max_msg_bits: i64,
    #[serde(rename = "max_msg_cells")]
    pub max_msg_cells: i64,
    #[serde(rename = "max_library_cells")]
    pub max_library_cells: i64,
    #[serde(rename = "max_vm_data_depth")]
    pub max_vm_data_depth: i32,
    #[serde(rename = "max_ext_msg_size")]
    pub max_ext_msg_size: i64,
    #[serde(rename = "max_ext_msg_depth")]
    pub max_ext_msg_depth: i32,
    #[serde(rename = "max_acc_state_cells", skip_serializing_if = "Option::is_none")]
    pub max_acc_state_cells: Option<i64>,
    #[serde(rename = "max_acc_state_bits", skip_serializing_if = "Option::is_none")]
    pub max_acc_state_bits: Option<i64>,
}

impl SizeLimitsConfig {
    pub fn new(max_msg_bits: i64, max_msg_cells: i64, max_library_cells: i64, max_vm_data_depth: i32, max_ext_msg_size: i64, max_ext_msg_depth: i32) -> SizeLimitsConfig {
        SizeLimitsConfig {
            max_msg_bits,
            max_msg_cells,
            max_library_cells,
            max_vm_data_depth,
            max_ext_msg_size,
            max_ext_msg_depth,
            max_acc_state_cells: None,
            max_acc_state_bits: None,
        }
    }
}


