/*
 * REST api to TON blockchain explorer
 *
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@tonkeeper.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct StorageProvider {
    #[serde(rename = "address")]
    pub address: String,
    #[serde(rename = "accept_new_contracts")]
    pub accept_new_contracts: bool,
    #[serde(rename = "rate_per_mb_day")]
    pub rate_per_mb_day: i64,
    #[serde(rename = "max_span")]
    pub max_span: i64,
    #[serde(rename = "minimal_file_size")]
    pub minimal_file_size: i64,
    #[serde(rename = "maximal_file_size")]
    pub maximal_file_size: i64,
}

impl StorageProvider {
    pub fn new(address: String, accept_new_contracts: bool, rate_per_mb_day: i64, max_span: i64, minimal_file_size: i64, maximal_file_size: i64) -> StorageProvider {
        StorageProvider {
            address,
            accept_new_contracts,
            rate_per_mb_day,
            max_span,
            minimal_file_size,
            maximal_file_size,
        }
    }
}


