/*
 * REST api to TON blockchain explorer
 *
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@tonkeeper.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ValidatorsSet {
    #[serde(rename = "utime_since")]
    pub utime_since: i32,
    #[serde(rename = "utime_until")]
    pub utime_until: i32,
    #[serde(rename = "total")]
    pub total: i32,
    #[serde(rename = "main")]
    pub main: i32,
    #[serde(rename = "total_weight", skip_serializing_if = "Option::is_none")]
    pub total_weight: Option<i64>,
    #[serde(rename = "list")]
    pub list: Vec<crate::models::ValidatorsSetListInner>,
}

impl ValidatorsSet {
    pub fn new(utime_since: i32, utime_until: i32, total: i32, main: i32, list: Vec<crate::models::ValidatorsSetListInner>) -> ValidatorsSet {
        ValidatorsSet {
            utime_since,
            utime_until,
            total,
            main,
            total_weight: None,
            list,
        }
    }
}


