/*
 * REST api to TON blockchain explorer
 *
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@tonkeeper.com
 * Generated by: https://openapi-generator.tech
 */

/// WithdrawStakeAction : validator's participation in elections



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct WithdrawStakeAction {
    #[serde(rename = "amount")]
    pub amount: i64,
    #[serde(rename = "staker")]
    pub staker: Box<crate::models::AccountAddress>,
    #[serde(rename = "pool")]
    pub pool: Box<crate::models::AccountAddress>,
    #[serde(rename = "implementation")]
    pub implementation: crate::models::PoolImplementationType,
}

impl WithdrawStakeAction {
    /// validator's participation in elections
    pub fn new(amount: i64, staker: crate::models::AccountAddress, pool: crate::models::AccountAddress, implementation: crate::models::PoolImplementationType) -> WithdrawStakeAction {
        WithdrawStakeAction {
            amount,
            staker: Box::new(staker),
            pool: Box::new(pool),
            implementation,
        }
    }
}


