/*
 * REST api to TON blockchain explorer
 *
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@tonkeeper.com
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AccStatusChange {
    #[serde(rename = "acst_unchanged")]
    Unchanged,
    #[serde(rename = "acst_frozen")]
    Frozen,
    #[serde(rename = "acst_deleted")]
    Deleted,

}

impl ToString for AccStatusChange {
    fn to_string(&self) -> String {
        match self {
            Self::Unchanged => String::from("acst_unchanged"),
            Self::Frozen => String::from("acst_frozen"),
            Self::Deleted => String::from("acst_deleted"),
        }
    }
}

impl Default for AccStatusChange {
    fn default() -> AccStatusChange {
        Self::Unchanged
    }
}




