/*
 * REST api to TON blockchain explorer
 *
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@tonkeeper.com
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AccountStatus {
    #[serde(rename = "nonexist")]
    Nonexist,
    #[serde(rename = "uninit")]
    Uninit,
    #[serde(rename = "active")]
    Active,
    #[serde(rename = "frozen")]
    Frozen,

}

impl ToString for AccountStatus {
    fn to_string(&self) -> String {
        match self {
            Self::Nonexist => String::from("nonexist"),
            Self::Uninit => String::from("uninit"),
            Self::Active => String::from("active"),
            Self::Frozen => String::from("frozen"),
        }
    }
}

impl Default for AccountStatus {
    fn default() -> AccountStatus {
        Self::Nonexist
    }
}




