/*
 * REST api to TON blockchain explorer
 *
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@tonkeeper.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Auctions {
    #[serde(rename = "data")]
    pub data: Vec<crate::models::Auction>,
    #[serde(rename = "total")]
    pub total: i64,
}

impl Auctions {
    pub fn new(data: Vec<crate::models::Auction>, total: i64) -> Auctions {
        Auctions {
            data,
            total,
        }
    }
}


