/*
 * REST api to TON blockchain explorer
 *
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@tonkeeper.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct DnsRecord {
    #[serde(rename = "wallet", skip_serializing_if = "Option::is_none")]
    pub wallet: Option<Box<crate::models::WalletDns>>,
    #[serde(rename = "next_resolver", skip_serializing_if = "Option::is_none")]
    pub next_resolver: Option<String>,
    #[serde(rename = "sites")]
    pub sites: Vec<String>,
    /// tonstorage bag id
    #[serde(rename = "storage", skip_serializing_if = "Option::is_none")]
    pub storage: Option<String>,
}

impl DnsRecord {
    pub fn new(sites: Vec<String>) -> DnsRecord {
        DnsRecord {
            wallet: None,
            next_resolver: None,
            sites,
            storage: None,
        }
    }
}


