/*
 * REST api to TON blockchain explorer
 *
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@tonkeeper.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetRawBlockProof200ResponseStepsInnerLiteServerBlockLinkBack {
    #[serde(rename = "to_key_block")]
    pub to_key_block: bool,
    #[serde(rename = "from")]
    pub from: Box<crate::models::BlockRaw>,
    #[serde(rename = "to")]
    pub to: Box<crate::models::BlockRaw>,
    #[serde(rename = "dest_proof")]
    pub dest_proof: String,
    #[serde(rename = "proof")]
    pub proof: String,
    #[serde(rename = "state_proof")]
    pub state_proof: String,
}

impl GetRawBlockProof200ResponseStepsInnerLiteServerBlockLinkBack {
    pub fn new(to_key_block: bool, from: crate::models::BlockRaw, to: crate::models::BlockRaw, dest_proof: String, proof: String, state_proof: String) -> GetRawBlockProof200ResponseStepsInnerLiteServerBlockLinkBack {
        GetRawBlockProof200ResponseStepsInnerLiteServerBlockLinkBack {
            to_key_block,
            from: Box::new(from),
            to: Box::new(to),
            dest_proof,
            proof,
            state_proof,
        }
    }
}


