/*
 * REST api to TON blockchain explorer
 *
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@tonkeeper.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct NftCollection {
    #[serde(rename = "address")]
    pub address: String,
    #[serde(rename = "next_item_index")]
    pub next_item_index: i64,
    #[serde(rename = "owner", skip_serializing_if = "Option::is_none")]
    pub owner: Option<Box<crate::models::AccountAddress>>,
    #[serde(rename = "raw_collection_content")]
    pub raw_collection_content: String,
    #[serde(rename = "metadata", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<::std::collections::HashMap<String, serde_json::Value>>,
    #[serde(rename = "previews", skip_serializing_if = "Option::is_none")]
    pub previews: Option<Vec<crate::models::ImagePreview>>,
    #[serde(rename = "approved_by")]
    pub approved_by: Vec<ApprovedBy>,
}

impl NftCollection {
    pub fn new(address: String, next_item_index: i64, raw_collection_content: String, approved_by: Vec<ApprovedBy>) -> NftCollection {
        NftCollection {
            address,
            next_item_index,
            owner: None,
            raw_collection_content,
            metadata: None,
            previews: None,
            approved_by,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ApprovedBy {
    #[serde(rename = "getgems")]
    Getgems,
    #[serde(rename = "tonkeeper")]
    Tonkeeper,
    #[serde(rename = "ton.diamonds")]
    TonPeriodDiamonds,
}

impl Default for ApprovedBy {
    fn default() -> ApprovedBy {
        Self::Getgems
    }
}

