/*
 * REST api to TON blockchain explorer
 *
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@tonkeeper.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TonConnectProof200Response {
    #[serde(rename = "token")]
    pub token: String,
}

impl TonConnectProof200Response {
    pub fn new(token: String) -> TonConnectProof200Response {
        TonConnectProof200Response {
            token,
        }
    }
}


