/*
 * REST api to TON blockchain explorer
 *
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@tonkeeper.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Validators {
    #[serde(rename = "elect_at")]
    pub elect_at: i64,
    #[serde(rename = "elect_close")]
    pub elect_close: i64,
    #[serde(rename = "min_stake")]
    pub min_stake: i64,
    #[serde(rename = "total_stake")]
    pub total_stake: i64,
    #[serde(rename = "validators")]
    pub validators: Vec<crate::models::Validator>,
}

impl Validators {
    pub fn new(elect_at: i64, elect_close: i64, min_stake: i64, total_stake: i64, validators: Vec<crate::models::Validator>) -> Validators {
        Validators {
            elect_at,
            elect_close,
            min_stake,
            total_stake,
            validators,
        }
    }
}


