/*
 * REST api to TON blockchain explorer
 *
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@tonkeeper.com
 * Generated by: https://openapi-generator.tech
 */

/// BlockchainConfig28 : The configuration for the Catchain protocol.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BlockchainConfig28 {
    #[serde(rename = "mc_catchain_lifetime")]
    pub mc_catchain_lifetime: i64,
    #[serde(rename = "shard_catchain_lifetime")]
    pub shard_catchain_lifetime: i64,
    #[serde(rename = "shard_validators_lifetime")]
    pub shard_validators_lifetime: i64,
    #[serde(rename = "shard_validators_num")]
    pub shard_validators_num: i64,
    #[serde(rename = "flags", skip_serializing_if = "Option::is_none")]
    pub flags: Option<i32>,
    #[serde(rename = "shuffle_mc_validators", skip_serializing_if = "Option::is_none")]
    pub shuffle_mc_validators: Option<bool>,
}

impl BlockchainConfig28 {
    /// The configuration for the Catchain protocol.
    pub fn new(mc_catchain_lifetime: i64, shard_catchain_lifetime: i64, shard_validators_lifetime: i64, shard_validators_num: i64) -> BlockchainConfig28 {
        BlockchainConfig28 {
            mc_catchain_lifetime,
            shard_catchain_lifetime,
            shard_validators_lifetime,
            shard_validators_num,
            flags: None,
            shuffle_mc_validators: None,
        }
    }
}


