/*
 * REST api to TON blockchain explorer
 *
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@tonkeeper.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BlockchainAccountInspectMethodsInner {
    #[serde(rename = "id")]
    pub id: i64,
    #[serde(rename = "method")]
    pub method: String,
}

impl BlockchainAccountInspectMethodsInner {
    pub fn new(id: i64, method: String) -> BlockchainAccountInspectMethodsInner {
        BlockchainAccountInspectMethodsInner {
            id,
            method,
        }
    }
}


