/*
 * REST api to TON blockchain explorer
 *
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@tonkeeper.com
 * Generated by: https://openapi-generator.tech
 */

/// BlockchainConfig29 : The configuration for the consensus protocol above catchain.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BlockchainConfig29 {
    #[serde(rename = "flags", skip_serializing_if = "Option::is_none")]
    pub flags: Option<i32>,
    #[serde(rename = "new_catchain_ids", skip_serializing_if = "Option::is_none")]
    pub new_catchain_ids: Option<bool>,
    #[serde(rename = "round_candidates")]
    pub round_candidates: i64,
    #[serde(rename = "next_candidate_delay_ms")]
    pub next_candidate_delay_ms: i64,
    #[serde(rename = "consensus_timeout_ms")]
    pub consensus_timeout_ms: i64,
    #[serde(rename = "fast_attempts")]
    pub fast_attempts: i64,
    #[serde(rename = "attempt_duration")]
    pub attempt_duration: i64,
    #[serde(rename = "catchain_max_deps")]
    pub catchain_max_deps: i64,
    #[serde(rename = "max_block_bytes")]
    pub max_block_bytes: i64,
    #[serde(rename = "max_collated_bytes")]
    pub max_collated_bytes: i64,
    #[serde(rename = "proto_version", skip_serializing_if = "Option::is_none")]
    pub proto_version: Option<i64>,
    #[serde(rename = "catchain_max_blocks_coeff", skip_serializing_if = "Option::is_none")]
    pub catchain_max_blocks_coeff: Option<i64>,
}

impl BlockchainConfig29 {
    /// The configuration for the consensus protocol above catchain.
    pub fn new(round_candidates: i64, next_candidate_delay_ms: i64, consensus_timeout_ms: i64, fast_attempts: i64, attempt_duration: i64, catchain_max_deps: i64, max_block_bytes: i64, max_collated_bytes: i64) -> BlockchainConfig29 {
        BlockchainConfig29 {
            flags: None,
            new_catchain_ids: None,
            round_candidates,
            next_candidate_delay_ms,
            consensus_timeout_ms,
            fast_attempts,
            attempt_duration,
            catchain_max_deps,
            max_block_bytes,
            max_collated_bytes,
            proto_version: None,
            catchain_max_blocks_coeff: None,
        }
    }
}


