/*
 * REST api to TON blockchain explorer
 *
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@tonkeeper.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct DomainNames {
    #[serde(rename = "domains")]
    pub domains: Vec<String>,
}

impl DomainNames {
    pub fn new(domains: Vec<String>) -> DomainNames {
        DomainNames {
            domains,
        }
    }
}


