/*
 * REST api to TON blockchain explorer
 *
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@tonkeeper.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct JettonInfo {
    #[serde(rename = "mintable")]
    pub mintable: bool,
    #[serde(rename = "total_supply")]
    pub total_supply: String,
    #[serde(rename = "metadata")]
    pub metadata: Box<crate::models::JettonMetadata>,
    #[serde(rename = "verification")]
    pub verification: crate::models::JettonVerificationType,
    #[serde(rename = "holders_count")]
    pub holders_count: i32,
}

impl JettonInfo {
    pub fn new(mintable: bool, total_supply: String, metadata: crate::models::JettonMetadata, verification: crate::models::JettonVerificationType, holders_count: i32) -> JettonInfo {
        JettonInfo {
            mintable,
            total_supply,
            metadata: Box::new(metadata),
            verification,
            holders_count,
        }
    }
}


