/*
 * REST api to TON blockchain explorer
 *
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@tonkeeper.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Transactions {
    #[serde(rename = "transactions")]
    pub transactions: Vec<crate::models::Transaction>,
}

impl Transactions {
    pub fn new(transactions: Vec<crate::models::Transaction>) -> Transactions {
        Transactions {
            transactions,
        }
    }
}


