/*
 * REST api to TON blockchain explorer
 *
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@tonkeeper.com
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TransactionType {
    #[serde(rename = "TransOrd")]
    TransOrd,
    #[serde(rename = "TransTickTock")]
    TransTickTock,
    #[serde(rename = "TransSplitPrepare")]
    TransSplitPrepare,
    #[serde(rename = "TransSplitInstall")]
    TransSplitInstall,
    #[serde(rename = "TransMergePrepare")]
    TransMergePrepare,
    #[serde(rename = "TransMergeInstall")]
    TransMergeInstall,
    #[serde(rename = "TransStorage")]
    TransStorage,

}

impl ToString for TransactionType {
    fn to_string(&self) -> String {
        match self {
            Self::TransOrd => String::from("TransOrd"),
            Self::TransTickTock => String::from("TransTickTock"),
            Self::TransSplitPrepare => String::from("TransSplitPrepare"),
            Self::TransSplitInstall => String::from("TransSplitInstall"),
            Self::TransMergePrepare => String::from("TransMergePrepare"),
            Self::TransMergeInstall => String::from("TransMergeInstall"),
            Self::TransStorage => String::from("TransStorage"),
        }
    }
}

impl Default for TransactionType {
    fn default() -> TransactionType {
        Self::TransOrd
    }
}




